development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: twilio_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: twilio_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

# Automatically handled by Heroku. Sweet!
production:

